my_plug_planner_controllers:
    resource: '../src/MyPlugPlanner/ChargePoint/Entrypoint/Controller'
    type: attribute

iberdrola_api_controllers:
    resource: '../src/IberdrolaApi/ChargePoint/Entrypoint/Controller'
    type: attribute
