app_controllers:
    resource: '../src/App/ChargePoint/Entrypoint/Controller'
    type: attribute

iberdrola_api_controllers:
    resource: '../src/IberdrolaApi/ChargePoint/Entrypoint/Controller'
    type: attribute
