my_plug_planner_controllers:
    resource: '../src/MyPlugPlanner/ChargePoint/Entrypoint/Controller'
    type: attribute

iberdrola_api_charge_controller:
    resource: '../src/IberdrolaApi/Charge/Entrypoint/Controller'
    type: attribute

iberdrola_api_charge_point_controller:
    resource: '../src/IberdrolaApi/ChargePoint/Entrypoint/Controller'
    type: attribute
