services:
    _defaults:
        autowire: true
        autoconfigure: true

    Shared\Tests\Behat\:
        resource: '../tests/Shared/Behat/*'
        bind:
            Symfony\Component\HttpKernel\Kernel $kernel: '@kernel'

    PcComponentes\OpenApiMessagingContext\Utils\RequestHistory:
        class: PcComponentes\OpenApiMessagingContext\Utils\RequestHistory
        public: true