# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Shared\Infrastructure\Entrypoint\Requests\BaseRequestResolver:
        arguments:
            $validator: '@validator'
        tags:
            - { name: controller.argument_value_resolver, priority: 100 }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    # Shared Context
    Shared\:
        resource: '../src/Shared/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Entity/'
            - '../src/Repository/'
            - '../src/Shared/Infrastructure/Entrypoint/Requests/BaseRequestResolver.php'

    # MyPlugPlanner Context
    MyPlugPlanner\:
        resource: '../src/MyPlugPlanner/'
        exclude:
            - '../src/MyPlugPlanner/DependencyInjection/'
            - '../src/MyPlugPlanner/Kernel.php'

    # IberdrolaApi Context
    IberdrolaApi\:
        resource: '../src/IberdrolaApi/'
        exclude:
            - '../src/IberdrolaApi/DependencyInjection/'
            - '../src/IberdrolaApi/Kernel.php'
        bind:
            Symfony\Contracts\HttpClient\HttpClientInterface $iberdrolaApiClient: '@iberdrola.api.client'
            Symfony\Contracts\HttpClient\HttpClientInterface $iberdrolaPublicApiClient: '@iberdrola.public-api.client'

    iberdrola.api.client:
        class: Symfony\Component\HttpClient\HttpClient
        factory: [ Symfony\Component\HttpClient\HttpClient, 'create' ]
        arguments:
            $defaultOptions:
                base_uri: '%env(IBERDROLA_API_URL)%'
                http_version: '1.1'
                headers:
                    Accept: 'application/json'
                    Content-Type: 'application/json'
                    Plataforma: 'Android'
                    versionApp: 'ANDROID-4.28.11'
                    User-Agent: 'Iberdrola/4.28.10/Dalvik/2.1.0 (Linux; U; Android 13; M2101K6G Build/TKQ1.221013.002)'

    iberdrola.public-api.client:
        class: Symfony\Component\HttpClient\HttpClient
        factory: [ Symfony\Component\HttpClient\HttpClient, 'create' ]
        arguments:
            $defaultOptions:
                base_uri: '%env(IBERDROLA_PUBLIC_API_URL)%'
                http_version: '1.1'
                headers:
                    Accept: 'application/json'
                    Content-Type: 'application/json'
                    sec-ch-ua: '"Chromium";v="128", "Not;A=Brand";v="24", "Microsoft Edge";v="128"'
                    sec-ch-ua-platform: '"Linux"'
                    Accepted-Language: 'es-ES,es;q=0.9,en;q=0.8'
                    User-Agent: 'PostmanRuntime/7.32.0'
                    Connection: 'keep-alive'
                    Timeout: 180
                    Cache-Control: 'no-cache'