#!/bin/bash
set -e

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE USER '$MYSQL_READONLY_USER'@'%' IDENTIFIED BY '$MYSQL_READONLY_PASSWORD';
    GRANT SELECT ON *.* TO '$MYSQL_READONLY_USER'@'%';
FLUSH PRIVILEGES;
EOSQL